# Generated by Django 6.0.3 on 2026-03-20 12:38

import habits.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='next_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='execution_time',
            field=models.PositiveIntegerField(validators=[habits.validators.validate_execution_time]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(default=1, validators=[habits.validators.validate_periodicity]),
        ),
    ]
